server:
  port: 8080
  #  Aplicacion

spring:
  #   Aplicacion
  application:
    name: portal-web
  #    Base de datos
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  #Jpa
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

jwt:
  secret_key: rf8w4I2egxLZci1xSUZo0NpWQnM1LiEXTfhd8foroHVwo47UL9BLwHpq4Ct6RYW5Yv9kR0pin41CMk9at0X4OA== #${JWT_SECRET_KEY}
  expiration: 60000 #/${JWT_EXPIRATION}
  refresh-token:
    expiration: 300000 #${JWT_REFRESH_TOKEN_EXPIRATION}
